import html
from datetime import datetime

def generate_html_report(analysis_results: dict, input_code_snippet: str) -> str:
    """
    Generates an HTML report string from the XSS analysis results.

    Args:
        analysis_results (dict): The dictionary output from analyze_code_for_xss.
        input_code_snippet (str): The original code snippet that was analyzed.

    Returns:
        str: An HTML string representing the report.
    """

    report_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    language = analysis_results.get("language_analyzed", "N/A")
    vuln_count = analysis_results.get("vulnerability_count", 0)
    findings = analysis_results.get("findings", [])
    error_message = analysis_results.get("error")

    # Escape functions for HTML content
    def escape(text):
        if text is None:
            return "N/A"
        return html.escape(str(text))

    # Start HTML structure
    html_report = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XSS Analysis Report</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 20px; background-color: #f9f9f9; color: #333; }}
        .container {{ background-color: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #d9534f; border-bottom: 2px solid #d9534f; padding-bottom: 10px; }}
        h2 {{ color: #5bc0de; margin-top: 30px; border-bottom: 1px solid #eee; padding-bottom: 5px; }}
        table {{ border-collapse: collapse; width: 100%; margin-top: 15px; box-shadow: 0 2px 3px rgba(0,0,0,0.1); }}
        th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; font-size: 0.9em; }}
        th {{ background-color: #f2f2f2; color: #555; }}
        tr:nth-child(even) {{ background-color: #f9f9f9; }}
        tr:hover {{ background-color: #f1f1f1; }}
        .payload, .code-snippet code {{
            font-family: 'Courier New', Courier, monospace;
            background-color: #eef;
            padding: 2px 5px;
            border-radius: 4px;
            font-size: 0.95em;
            word-break: break-all;
        }}
        .code-snippet {{
            background-color: #f8f8f8;
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 4px;
            margin-top: 5px;
            max-height: 200px;
            overflow-y: auto;
        }}
        .summary p, .error-message p {{ margin: 5px 0; }}
        .summary strong {{ color: #337ab7; }}
        .error-message {{ background-color: #f2dede; color: #a94442; border: 1px solid #ebccd1; padding: 10px; border-radius: 4px; margin-top: 20px; }}
        .footer {{ margin-top: 30px; text-align: center; font-size: 0.8em; color: #777; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>XSS Analysis Report</h1>

        <div class="summary">
            <p><strong>Report Generated:</strong> {escape(report_time)}</p>
            <p><strong>Language Analyzed:</strong> {escape(language)}</p>
            <p><strong>Total Potential Vulnerabilities Found:</strong> {vuln_count}</p>
        </div>

        <h2>Source Code Analyzed:</h2>
        <div class="code-snippet">
            <pre><code>{escape(input_code_snippet)}</code></pre>
        </div>
"""

    if error_message:
        html_report += f"""
        <div class="error-message">
            <p><strong>Analysis Error:</strong> {escape(error_message)}</p>
        </div>
"""
    elif vuln_count > 0:
        html_report += """
        <h2>Detailed Findings:</h2>
        <table>
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Tag</th>
                    <th>Attribute</th>
                    <th>Line No.</th>
                    <th>Payload/Pattern</th>
                    <th>Surrounding Code</th>
                </tr>
            </thead>
            <tbody>
"""
        for finding in findings:
            html_report += f"""
                <tr>
                    <td>{escape(finding.get("finding_type"))}</td>
                    <td>{escape(finding.get("tag"))}</td>
                    <td>{escape(finding.get("attribute"))}</td>
                    <td>{escape(finding.get("line_number"))}</td>
                    <td><span class="payload">{escape(finding.get("payload"))}</span></td>
                    <td><span class="payload">{escape(finding.get("surrounding_code"))}</span></td>
                </tr>
"""
        html_report += """
            </tbody>
        </table>
"""
    else:
        html_report += """
        <h2>Findings:</h2>
        <p>No potential XSS vulnerabilities found by the current engine.</p>
"""

    html_report += """
        <div class="footer">
            <p>Report generated by XSS Detection Tool.</p>
        </div>
    </div>
</body>
</html>
"""
    return html_report

if __name__ == '__main__':
    # Example usage for testing the reporter directly
    mock_analysis_results_vulnerable = {
        "language_analyzed": "html",
        "vulnerability_count": 2,
        "findings": [
            {
                "finding_type": "event_handler",
                "payload": "alert('XSS1')",
                "tag": "img",
                "attribute": "onerror",
                "line_number": 1,
                "surrounding_code": "<img src='x' onerror='alert(\"XSS1\")'>"
            },
            {
                "finding_type": "javascript_uri",
                "payload": "javascript:alert('XSS2')",
                "tag": "a",
                "attribute": "href",
                "line_number": 2,
                "surrounding_code": "<a href='javascript:alert(\"XSS2\")'>Click</a>"
            }
        ],
        "summary": "Found 2 potential XSS vulnerabilities.",
        "error": None,
    }
    mock_input_code_vulnerable = "<img src='x' onerror='alert(\"XSS1\")'>\n<a href='javascript:alert(\"XSS2\")'>Click</a>"

    report_html_vuln = generate_html_report(mock_analysis_results_vulnerable, mock_input_code_vulnerable)
    with open("test_report_vulnerable.html", "w", encoding="utf-8") as f:
        f.write(report_html_vuln)
    print("Generated test_report_vulnerable.html")

    mock_analysis_results_clean = {
        "language_analyzed": "html",
        "vulnerability_count": 0,
        "findings": [],
        "summary": "No potential XSS vulnerabilities found.",
        "error": None,
    }
    mock_input_code_clean = "<p>This is a clean paragraph.</p>"
    report_html_clean = generate_html_report(mock_analysis_results_clean, mock_input_code_clean)
    with open("test_report_clean.html", "w", encoding="utf-8") as f:
        f.write(report_html_clean)
    print("Generated test_report_clean.html")

    mock_analysis_results_error = {
        "language_analyzed": "unknown",
        "vulnerability_count": 0,
        "findings": [],
        "summary": "Analysis error.",
        "error": "Unsupported language provided.",
    }
    mock_input_code_error = "some code"
    report_html_error = generate_html_report(mock_analysis_results_error, mock_input_code_error)
    with open("test_report_error.html", "w", encoding="utf-8") as f:
        f.write(report_html_error)
    print("Generated test_report_error.html")
